#!/bin/bash

if [[ ! -x $(command -v rsync) ]]; then
  echo no rsync found!
  exit 1
fi

#1 获取输入参数的个数；如果没有参数，直接退出
pcount=$#
if ((pcount==0)); then
  echo no args!
  exit
fi

#2 获取文件名称
p1=$1
fname=$(basename $p1)
echo fname=$fname

#3 获取文件绝对路径
pdir=$(cd -P $(dirname $p1); pwd)
echo pdir=$pdir

#4 获取当前用户名称
usr=$(whoami)

#5 循环体
for ((host=2; host<4; host++)); do
  echo ---hadoop${host}---
  rsync -rvl $pdir/$fname ${usr}@hadoop${host}:${pdir}
done
