#!/bin/bash

if [[ -x $(command -v rsync) ]]; then
  echo yes > /dev/null
else
  echo no rsync found!  
  exit 1
fi

pcount=$#
if ((pcount==0)); then
  echo no args!
  exit
fi

p1=$1
fname=$(basename $p1)
echo fname=$fname

pdir=$(cd -P $(dirname $p1); pwd)
echo pdir=$pdir

usr=$(whoami)

for ((host=2; host<4; host++)); do
  echo ---hadoop${host}---
  rsync -rvl $pdir/$fname ${usr}@hadoop${host}:${pdir}
done
